package drl;

import nl.jqno.foobal.domain.*;

dialect "mvel"

rule "Last year's outcome"
when
	$result  : ScoreKeeper()
	$outcome : Outcome( homeTeam == $result.homeTeam,
	                    outTeam  == $result.outTeam,
	                    $latestDate : date )
	not Outcome( homeTeam == $result.homeTeam,
	             outTeam  == $result.outTeam,
	             $latestDate < date )
then
	$result.add($outcome.homeScore, $outcome.outScore);
end

rule "There was no outcome last year"
when
	$result : ScoreKeeper()
	not Outcome( homeTeam == $result.homeTeam,
	             outTeam  == $result.outTeam )
then
	$result.add(0, 0)
end
